# tun2socks配置示例

# 设备配置
device: tun0
mtu: 1500
loglevel: info

# 多代理配置（支持负载均衡）
proxy:
  - socks5://127.0.0.1:1080
  - socks5://127.0.0.1:1081
  - socks5://127.0.0.1:1082

# 健康检查配置
health-check:
  enable: true                    # 启用健康检查
  interval: 30s                   # 检查间隔30秒
  timeout: 5s                     # 检查超时5秒
  url: "http://www.google.com"    # 检查目标URL

# REST API配置
restapi: 127.0.0.1:9090

# 网络配置
tcp-sndbuf: 4096
tcp-rcvbuf: 4096
tcp-auto-tuning: true

# UDP超时
udp-timeout: 60s

# TUN设备设置命令
tun-pre-up: "echo 'Setting up TUN device'"
tun-post-up: "echo 'TUN device ready'"